In [7]:
import pandas as pd

# Read the CSV file, skipping lines with parsing errors
data = pd.read_excel('/content/Product_Rating_last_3_month_data.xlsx')

# Display the first few rows of the DataFrame
data.head()

,id,Product_id,Product_flavor_id,Shopper_id,User_id,Orderitem_id,description,images,rating,rating_reason,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,78602,7126,14960,1835820409595680000,1000268,1095787,NaN,[],5,Product Price,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaT
1,78603,7521,15874,4041237846491919872,1000268,1092834,Excellent thanks ����,[],5,Product Price,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaT
2,78604,6869,14289,2070306052036339968,1000268,893829,Fully satiafied,[],5,Product Quality,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaT
3,78605,6364,14296,3509748335361169920,1000563,1110946,Thank you priceoye for providing me with A24 f...,[],4,Product Price,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaT
4,78606,7456,15715,1586268211147,1000563,1099255,This is my 4th purchase from PriceOye._x000D_\...,You should give estimate of 7 days in the fir...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaT

In [8]:


# Assuming your DataFrame is named 'data' and the column containing Product IDs is 'Product_id'
top_product_counts = data['Product_id'].value_counts().head(3)

# Display the top 3 Product ID counts
print(top_product_counts)

Product_id
7126    429
6194    296
7040    258
Name: count, dtype: int64

Now, On the basis of above Product_ids, I'll able to identify Products from Product table (Product table and Product Rating having 1 to Many Relationship in database) in my database.
List of those are as follows:
1. Xiaomi Redmi 12
2. M10 TWS Wireless Bluetooth Earbuds
3. Air 31 TWS Transparent Earbuds

Afterwards, getting this inside We maintain more stocks for above products and Do Marketing in a more appropriate way to grab clients.